[package]
name = "bcrypt-generator"
version = "0.1.0"
authors = ["Cheng JIANG <cheng.jiang@outlook.fr>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
clap = { version = "2.33.0", features = ["yaml", "suggestions", "color"] }
bcrypt = "0.5.0"

